// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/u-shylianok/golang-test-tasks/task05/internal/model"
)

// MockAd is a mock of Ad interface.
type MockAd struct {
	ctrl     *gomock.Controller
	recorder *MockAdMockRecorder
}

// MockAdMockRecorder is the mock recorder for MockAd.
type MockAdMockRecorder struct {
	mock *MockAd
}

// NewMockAd creates a new mock instance.
func NewMockAd(ctrl *gomock.Controller) *MockAd {
	mock := &MockAd{ctrl: ctrl}
	mock.recorder = &MockAdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAd) EXPECT() *MockAdMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAd) Create(ad model.Ad) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ad)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdMockRecorder) Create(ad interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAd)(nil).Create), ad)
}

// Get mocks base method.
func (m *MockAd) Get(adId int, fields []string) (model.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", adId, fields)
	ret0, _ := ret[0].(model.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdMockRecorder) Get(adId, fields interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAd)(nil).Get), adId, fields)
}

// List mocks base method.
func (m *MockAd) List(sortBy, order string) ([]model.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", sortBy, order)
	ret0, _ := ret[0].([]model.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAdMockRecorder) List(sortBy, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAd)(nil).List), sortBy, order)
}
