version: "3.7"

services:
  u-shylianok-task05-pg:
    build:
      context: ./build/db
      target: u-shylianok-task05-pg
    image: u-shylianok-task05-pg:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
    container_name: u-shylianok-task05-pg

  u-shylianok-task05-app:
    build:
      context: ./build/app
      target: u-shylianok-task05-app
    image: u-shylianok-task05-app:latest
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - APP_PORT=8000
      - DB_HOST=u-shylianok-task05-pg
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DBNAME=postgres
      - DB_SSL=disable
    depends_on:
      - u-shylianok-task05-pg

    container_name: u-shylianok-task05-app
